# Generated by Django 5.2.4 on 2025-08-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('Emitida', 'Emitida'), ('Aprobada', 'Aprobada'), ('Cancelada', 'Cancelada'), ('Recibida', 'Recibida'), ('Faltante', 'Faltante')], default='Emitida', max_length=20),
        ),
    ]
